Theguyhere0/villager-defense-minigame

src/me/theguyhere/villagerdefense/GUI/Inventories.java, src/me/theguyhere/villagerdefense/GUI/InventoryEvents.java, src/me/theguyhere/villagerdefense/game/models/Arena.java, src/me/theguyhere/villagerdefense/game/models/Kits.java, src/plugin.yml
- Fixed an issue where the "none" option was broken for kit selection
- Merchant now gets a 10% rebate
- Fixed an issue where starting fresh with the plugin would break the spawn table button for arenas
- Small lore changes for merchant and typos
- Price of blacksmith and vampire adjusted
=> Bug fixes and small balancing

common/pom.xml, nms/common/pom.xml, nms/pom.xml, nms/v1_16_r3/pom.xml, nms/v1_17_r1/pom.xml, nms/v1_18_r1/pom.xml, nms/v1_18_r2/pom.xml, plugin/pom.xml, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/Main.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/CommandTab.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/Commands.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/GameManager.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/arenas/Arena.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/InventoryListener.java, plugin/src/main/resources/plugin.yml, pom.xml
- Added `/vd reload` to reload internal data of the plugin and check for updates, replacing `config.yml` if missing
- Added another line to config.yml outdated error to remind of updating all else before itself
- Moved kicking and wiping arena to be automatically done when setting closed status
- Fixed issue with console color
- Added color to world checks and other console warnings
=> Hotfix 1.1.1

plugin/src/main/java/me/theguyhere/villagerdefense/plugin/GUI/Inventories.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/GUI/InventoryItems.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/Main.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/Commands.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/exceptions/InvalidLanguageKeyException.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/displays/ArenaBoard.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/displays/InfoBoard.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/displays/Leaderboard.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/displays/Portal.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/Challenge.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/EnchantingBook.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/GameItems.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/GameManager.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/Tasks.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/arenas/Arena.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/kits/Kit.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/AbilityListener.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/ArenaListener.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/ChallengeListener.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/GameListener.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/InventoryListener.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/JoinListener.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/tools/LanguageManager.java, plugin/src/main/resources/config.yml, plugin/src/main/resources/languages/en_US.yml
- Created helper class to handle language data with less error
- Refined language file keys
- Fixed bugs where colors were missing after updating language file handling
- Fixed bugs where the right keys were not being called
=> Language manager class

nms/v1_16_r3/pom.xml, nms/v1_16_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_16_r3/VersionNMSManager.java, nms/v1_17_r1/pom.xml, nms/v1_17_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_17_r1/VersionNMSManager.java, nms/v1_18_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_18_r1/VersionNMSManager.java, nms/v1_18_r2/src/main/java/me.theguyhere.villagerdefense.nms.v1_18_r2/VersionNMSManager.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/Commands.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/arenas/Arena.java
- Changed world border particles from barriers to redstone dust
- Modified internal commands to drop "Arena" and just state the arena name
=> Refinements

plugin/src/main/java/me/theguyhere/villagerdefense/plugin/Main.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/Commands.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/displays/Leaderboard.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/inventories/Inventories.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/ArenaListener.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/ChallengeListener.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/GameListener.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/InventoryListener.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/JoinListener.java, plugin/src/main/resources/config.yml
- Added function for vd fix command to convert existing data over
- Handles player UUID instead of name for player data
- Fixed bug where players could drop challenge selector
- Fixed bug where ghost item would appear in inv when shift clicking a button that closes inventory
=> Track player using UUID

plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/Commands.java
- Fixed bug where `/vd fix` only updated one version number at a time per .yml file
=> vd fix handle version jump

plugin/src/main/java/me/theguyhere/villagerdefense/plugin/Main.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/Commands.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/CustomEffectsListener.java, plugin/src/main/resources/config.yml, plugin/src/main/resources/customEffects.yml
- Implemented ability to add custom effects at a certain wave or after a game
=> Custom effects

plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/Tasks.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/arenas/Arena.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/ArenaListener.java
- Added counter to time limit bar title
- Fixed a bug where wave one automatically ended (internal to dev build)
=> Wave time limit timer

plugin/src/main/java/me/theguyhere/villagerdefense/plugin/Main.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/CommandTab.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/Commands.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/tools/LanguageManager.java, plugin/src/main/resources/config.yml, plugin/src/main/resources/languages/en_US.yml
- Refactored command class
- Added pages for help command
- Added more information for help command
=> [CHANGE] Added more information to /vd help

plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/displays/Leaderboard.java
Now left blank because of title overflow whoops
=> [CHANGE] Filter leaderboard records w/o Offlineplayer

nms/pom.xml, nms/v1_16_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_16_r3/SpawnEntityLivingPacket.java, nms/v1_17_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_17_r1/SpawnEntityLivingPacket.java, nms/v1_18_r2/src/main/java/me.theguyhere.villagerdefense.nms.v1_18_r2/SpawnEntityLivingPacket.java, nms/v1_19_r1/pom.xml, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/BlockChangePacket.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/DataWatcherKey.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/DataWatcherPacketBuilder.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/EntityDestroyPacket.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/EntityHeadRotationPacket.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/EntityMetadataPacket.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/EntityTypeID.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/InboundPacketHandler.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/OpenSignEditorPacket.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/PacketEntityArmorStand.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/PacketEntityVillager.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/PacketSetter.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/SpawnEntityPacket.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/TileEntityDataPacket.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/VersionNMSManager.java, nms/v1_19_r1/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r1/VersionNMSPacket.java, plugin/pom.xml, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/tools/NMSVersion.java, pom.xml
- 1.19 support
- minor inconsequential change to all API handling for spawning entities
=> [ADDITION] 1.19 support

plugin/src/main/java/me/theguyhere/villagerdefense/plugin/Main.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/VDExpansion.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/CommandTab.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/Commands.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/InventoryListener.java, plugin/src/main/resources/plugin.yml
- Added admin commands to modify most attributes from the admin GUI using commands
- Fixed a bug that allowed for deleting the lobby while arenas were still active
- Code refactoring and grammar tweaking
- Removed `/vd open` and `/vd close` commands as they are now part of the admin commands
=> Arena commands

plugin/src/main/java/me/theguyhere/villagerdefense/plugin/Main.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/Tasks.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/ArenaListener.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/tools/LanguageManager.java, plugin/src/main/resources/config.yml, plugin/src/main/resources/languages/en_US.yml
- Added dialogue in the beginning of the game
- Minor writing tweaks
=> [ADDITION] Game lore and instructions

plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/AbilityListener.java
- Fixed bug that allowed for armor equipping while invisible
=> [CHANGE] Fixed ninja nerfing issue

common/pom.xml, nms/common/pom.xml, nms/pom.xml, nms/v1_16_r3/pom.xml, nms/v1_17_r1/pom.xml, nms/v1_18_r1/pom.xml, nms/v1_18_r2/pom.xml, nms/v1_19_r1/pom.xml, plugin/pom.xml, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/GameManager.java, plugin/src/main/resources/plugin.yml, pom.xml
- Fixed a bug where getting arena via Player doesn't do nullpointer protection
- Added other small nullpointer protections in the same class
=> Hotfix 1.2.1

common/pom.xml, nms/common/pom.xml, nms/pom.xml, nms/v1_16_r3/pom.xml, nms/v1_17_r1/pom.xml, nms/v1_18_r1/pom.xml, nms/v1_18_r2/pom.xml, nms/v1_19_r1/pom.xml, plugin/pom.xml, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/Tasks.java, plugin/src/main/resources/plugin.yml, pom.xml
- Fixed a bug where errors would be thrown in the console for trying to access weapon, armor, and consumables shop before wave 1
=> Hotfix 1.2.3

plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/achievements/AchievementChecker.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/InventoryListener.java, plugin/src/main/resources/languages/en_US.yml
- Fixed currency name issue from achievements
- Fixed broken kit buying
=> [CHANGE] Fixed bugs internal to release

plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/armor/Boots.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/armor/Chestplate.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/armor/Helmet.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/armor/Leggings.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/food/Beetroot.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/food/Bread.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/food/Carrot.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/food/EnchantedApple.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/food/GoldenApple.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/food/GoldenCarrot.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/food/Mutton.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/food/Steak.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/food/Totem.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/weapons/Ammo.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/weapons/Axe.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/weapons/Bow.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/weapons/Crossbow.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/weapons/Scythe.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/items/weapons/Sword.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/mobs/VDGhast.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/inventories/Inventories.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/InventoryListener.java
- Item generation in shops reworked for a more consistent feel
- Increased food efficacy (health return and price)
- Increased range of villagers for shops
- Lowered ghast health
=> Initial rebalance

nms/common/pom.xml, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/Main.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/CommandFixFiles.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/CommandReloadPlugin.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/arenas/Arena.java, plugin/src/main/resources/config.yml, plugin/src/main/resources/customEffects.yml
- Small code cleanup
- Reloading plugin is now delayed by 5 seconds and closes all arenas for safety
- Fixed a bug that said wave defeated was -1 if ended before game starts
- Created differentiation between custom effects that are triggered before leaving and after leaving an arena
- Small update to functions for moving data around
- Implemented checks for versions being too high
- Fixed implementation of fixing customEffects
=> Compatibility and refinement

common/pom.xml, nms/common/pom.xml, nms/pom.xml, nms/v1_16_r3/pom.xml, nms/v1_17_r1/pom.xml, nms/v1_18_r1/pom.xml, nms/v1_18_r2/pom.xml, nms/v1_19_r1/pom.xml, nms/v1_19_r2/pom.xml, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/BlockChangePacket.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/DataWatcherKey.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/DataWatcherPacketBuilder.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/EntityDestroyPacket.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/EntityHeadRotationPacket.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/EntityMetadataPacket.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/EntityTypeID.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/InboundPacketHandler.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/OpenSignEditorPacket.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/PacketEntityArmorStand.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/PacketEntityVillager.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/PacketSetter.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/SpawnEntityPacket.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/TileEntityDataPacket.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/VersionNMSManager.java, nms/v1_19_r2/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r2/VersionNMSPacket.java, plugin/pom.xml, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/tools/NMSVersion.java, plugin/src/main/resources/plugin.yml, pom.xml
=> Hotfix 1.2.5

common/pom.xml, nms/common/pom.xml, nms/pom.xml, nms/v1_16_r3/pom.xml, nms/v1_17_r1/pom.xml, nms/v1_18_r1/pom.xml, nms/v1_18_r2/pom.xml, nms/v1_19_r1/pom.xml, nms/v1_19_r2/pom.xml, plugin/pom.xml, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/Main.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/commands/Commands.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/game/models/arenas/Arena.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/inventories/Inventories.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/ArenaListener.java, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/listeners/CustomEffectsListener.java, plugin/src/main/resources/config.yml, plugin/src/main/resources/customEffects.yml, plugin/src/main/resources/plugin.yml, pom.xml
- Fixed a bug where the lower bounds for custom effects did not work
- Fixed a bug that made wolves and golems useless when spawned before wave 1 starts
- Fixed a typo for the button to add new arena saying "New Info Board"
- Fixed a bug that said the wave defeated was -1 if the game ended before the first wave started
- Removed absorption saving to prevent absorption duping bug
=> Hotfix 1.2.6

common/pom.xml, nms/common/pom.xml, nms/pom.xml, nms/v1_16_r3/pom.xml, nms/v1_17_r1/pom.xml, nms/v1_18_r1/pom.xml, nms/v1_18_r2/pom.xml, nms/v1_19_r1/pom.xml, nms/v1_19_r2/pom.xml, nms/v1_19_r3/pom.xml, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/BlockChangePacket.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/DataWatcherKey.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/DataWatcherPacketBuilder.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/EntityDestroyPacket.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/EntityHeadRotationPacket.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/EntityMetadataPacket.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/EntityTypeID.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/InboundPacketHandler.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/OpenSignEditorPacket.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/PacketEntityArmorStand.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/PacketEntityVillager.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/PacketSetter.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/SpawnEntityPacket.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/TileEntityDataPacket.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/VersionNMSManager.java, nms/v1_19_r3/src/main/java/me/theguyhere/villagerdefense/nms/v1_19_r3/VersionNMSPacket.java, plugin/pom.xml, plugin/src/main/java/me/theguyhere/villagerdefense/plugin/tools/NMSVersion.java, plugin/src/main/resources/plugin.yml, pom.xml
=> Hotfix 1.2.7
